apiVersion: v1
kind: Pod
metadata:
  name: clientpod
  labels:
    name: clientpod
    app: chat
spec:
  containers:
  - name: clientpod
    image: awinash21/client:latest
    ports:
         - containerPort: 8000
