apiVersion: v1
kind: Service
metadata:
  name: streamservice1
  labels:
    name: streamservice1
    app: chat
spec:
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer
  selector:
     name: servpod1
     app: chat
